// app/pages/finances.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { Plus, Trash2, Calendar as CalendarIcon, DollarSign, ArrowUpCircle, ArrowDownCircle } from 'lucide-vue-next'
import { format } from 'date-fns'

const route = useRoute()
const client = useSupabaseClient()
const user = useSupabaseUser()

const type = computed(() => route.query.type as 'payable' | 'receivable' | undefined)
const title = computed(() => type.value === 'payable' ? 'Contas a Pagar' : type.value === 'receivable' ? 'Contas a Receber' : 'Finanças')
const transactions = ref<any[]>([])
const loading = ref(false)

// Form state
const isAdding = ref(false)
const newTransaction = ref({
  title: '',
  amount: 0,
  transaction_date: format(new Date(), 'yyyy-MM-dd'),
  type: 'payable',
  status: 'pending'
})

const fetchTransactions = async () => {
  if (!user.value) return
  loading.value = true
  
  let query = client.from('finance_transactions').select('*').order('transaction_date', { ascending: true })
  
  if (type.value) {
    query = query.eq('type', type.value)
  }
  
  const { data, error } = await query
  
  if (error) {
    console.error('Error fetching transactions:', error)
  } else {
    transactions.value = data || []
  }
  loading.value = false
}

const addTransaction = async () => {
  if (!newTransaction.value.title || !newTransaction.value.amount) return
  
  const { error } = await client.from('finance_transactions').insert({
    ...newTransaction.value,
    user_id: user.value.id,
    type: type.value || newTransaction.value.type // Use query type if available, else form type
  })
  
  if (error) {
    console.error('Error adding transaction:', error)
  } else {
    isAdding.value = false
    newTransaction.value = {
      title: '',
      amount: 0,
      transaction_date: format(new Date(), 'yyyy-MM-dd'),
      type: type.value || 'payable',
      status: 'pending'
    }
    fetchTransactions()
  }
}

const deleteTransaction = async (id: number) => {
  if (!confirm('Tem certeza que deseja excluir?')) return
  const { error } = await client.from('finance_transactions').delete().eq('id', id)
  if (error) console.error('Error deleting:', error)
  else fetchTransactions()
}

const toggleStatus = async (transaction: any) => {
  const newStatus = transaction.status === 'paid' ? 'pending' : 'paid'
  const { error } = await client.from('finance_transactions').update({ status: newStatus }).eq('id', transaction.id)
  if (error) console.error('Error updating status:', error)
  else transaction.status = newStatus
}

watch(() => route.query.type, (newType) => {
  if (newType) {
    newTransaction.value.type = newType as string
  }
  fetchTransactions()
}, { immediate: true })

onMounted(() => {
  fetchTransactions()
})

const totalPending = computed(() => transactions.value.filter(t => t.status === 'pending').reduce((sum, t) => sum + Number(t.amount), 0))
const totalPaid = computed(() => transactions.value.filter(t => t.status === 'paid').reduce((sum, t) => sum + Number(t.amount), 0))
</script>

<template>
  <div class="p-8 max-w-4xl mx-auto space-y-8">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-3xl font-bold flex items-center gap-2">
           <ArrowUpCircle v-if="type === 'payable'" class="w-8 h-8 text-red-500" />
           <ArrowDownCircle v-if="type === 'receivable'" class="w-8 h-8 text-emerald-500" />
           {{ title }}
        </h1>
        <p class="text-muted-foreground">Gerencie seus pagamentos e recebimentos.</p>
      </div>
      <button @click="isAdding = !isAdding" class="px-4 py-2 bg-primary text-primary-foreground rounded-md flex items-center gap-2 hover:bg-primary/90">
        <Plus class="w-4 h-4" /> Novo
      </button>
    </div>

    <!-- Summary Cards -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <div class="p-4 rounded-lg border bg-card text-card-foreground shadow-sm">
        <div class="text-sm font-medium text-muted-foreground">Total Pendente</div>
        <div class="text-2xl font-bold">R$ {{ totalPending.toFixed(2) }}</div>
      </div>
      <div class="p-4 rounded-lg border bg-card text-card-foreground shadow-sm">
        <div class="text-sm font-medium text-muted-foreground">Total Realizado</div>
        <div class="text-2xl font-bold text-green-600">R$ {{ totalPaid.toFixed(2) }}</div>
      </div>
    </div>

    <!-- Add Form -->
    <div v-if="isAdding" class="p-4 rounded-lg border bg-muted/30 space-y-4">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div class="md:col-span-2">
          <label class="text-sm font-medium">Descrição</label>
          <input v-model="newTransaction.title" class="w-full px-3 py-2 rounded-md border bg-background" placeholder="Ex: Aluguel" />
        </div>
        <div>
          <label class="text-sm font-medium">Valor (R$)</label>
          <input v-model="newTransaction.amount" type="number" step="0.01" class="w-full px-3 py-2 rounded-md border bg-background" />
        </div>
        <div>
          <label class="text-sm font-medium">Data</label>
          <input v-model="newTransaction.transaction_date" type="date" class="w-full px-3 py-2 rounded-md border bg-background" />
        </div>
      </div>
      <div class="flex justify-end gap-2">
        <button @click="isAdding = false" class="px-3 py-2 text-sm text-muted-foreground hover:bg-accent rounded-md">Cancelar</button>
        <button @click="addTransaction" class="px-3 py-2 text-sm bg-primary text-primary-foreground rounded-md hover:bg-primary/90">Salvar</button>
      </div>
    </div>

    <!-- List -->
    <div class="space-y-2">
      <div v-if="loading" class="text-center py-8 text-muted-foreground">Carregando...</div>
      <div v-else-if="transactions.length === 0" class="text-center py-8 text-muted-foreground border border-dashed rounded-lg">
        Nenhum registro encontrado.
      </div>
      <div v-else v-for="t in transactions" :key="t.id" class="flex items-center justify-between p-4 rounded-lg border bg-card hover:bg-accent/50 transition-colors">
        <div class="flex items-center gap-4">
          <button @click="toggleStatus(t)" class="w-5 h-5 rounded-full border flex items-center justify-center transition-colors" :class="t.status === 'paid' ? 'bg-green-500 border-green-500 text-white' : 'border-muted-foreground'">
            <svg v-if="t.status === 'paid'" xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>
          </button>
          <div>
            <div class="font-medium" :class="{ 'line-through text-muted-foreground': t.status === 'paid' }">{{ t.title }}</div>
            <div class="text-xs text-muted-foreground flex items-center gap-2">
              <span>{{ format(new Date(t.transaction_date), 'dd/MM/yyyy') }}</span>
              <span v-if="!type" class="px-1.5 py-0.5 rounded-full text-[10px] uppercase border" :class="t.type === 'payable' ? 'bg-red-100 text-red-700 border-red-200' : 'bg-emerald-100 text-emerald-700 border-emerald-200'">
                {{ t.type === 'payable' ? 'A Pagar' : 'A Receber' }}
              </span>
            </div>
          </div>
        </div>
        <div class="flex items-center gap-4">
          <div class="font-bold" :class="t.type === 'payable' ? 'text-red-600' : 'text-emerald-600'">
            {{ t.type === 'payable' ? '-' : '+' }} R$ {{ Number(t.amount).toFixed(2) }}
          </div>
          <button @click="deleteTransaction(t.id)" class="text-muted-foreground hover:text-destructive transition-colors">
            <Trash2 class="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// app/(default)/finances/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { createClient } from '@/app/lib/supabase/Client';
import { useRouter } from 'next/navigation';
import { Plus, X, Edit2, Trash2, Wallet, TrendingUp, TrendingDown } from 'lucide-react';

export default function FinancesPage() {
  const [user, setUser] = useState<any>(null);
  const [transactions, setTransactions] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [editingTransaction, setEditingTransaction] = useState<any>(null);
  const [formData, setFormData] = useState({
    description: '',
    amount: '',
    type: 'expense' as 'income' | 'expense',
    category: '',
    date: new Date().toISOString().split('T')[0],
  });
  const router = useRouter();
  const client = createClient();

  useEffect(() => {
    const getUser = async () => {
      const { data: { user } } = await client.auth.getUser();
      if (!user) {
        router.push('/login');
        return;
      }
      setUser(user);
    };
    getUser();
  }, []);

  useEffect(() => {
    if (user) {
      fetchTransactions();
    }
  }, [user]);

  const fetchTransactions = async () => {
    if (!user) return;
    setLoading(true);

    const { data } = await client
      .from('finances')
      .select('*')
      .eq('user_id', user.id)
      .order('date', { ascending: false });

    if (data) setTransactions(data);
    setLoading(false);
  };

  const saveTransaction = async () => {
    if (!formData.description.trim() || !formData.amount || !user) return;

    const transactionData = {
      user_id: user.id,
      description: formData.description,
      amount: parseFloat(formData.amount),
      type: formData.type,
      category: formData.category || null,
      date: formData.date,
    };

    if (editingTransaction) {
      await client.from('finances').update(transactionData).eq('id', editingTransaction.id);
      setTransactions(transactions.map(t => t.id === editingTransaction.id ? { ...t, ...transactionData } : t));
    } else {
      const { data } = await client.from('finances').insert(transactionData).select().single();
      if (data) setTransactions([data, ...transactions]);
    }

    resetForm();
  };

  const deleteTransaction = async (id: number) => {
    await client.from('finances').delete().eq('id', id);
    setTransactions(transactions.filter(t => t.id !== id));
  };

  const editTransaction = (transaction: any) => {
    setEditingTransaction(transaction);
    setFormData({
      description: transaction.description,
      amount: transaction.amount.toString(),
      type: transaction.type,
      category: transaction.category || '',
      date: transaction.date,
    });
    setShowForm(true);
  };

  const resetForm = () => {
    setShowForm(false);
    setEditingTransaction(null);
    setFormData({
      description: '',
      amount: '',
      type: 'expense',
      category: '',
      date: new Date().toISOString().split('T')[0],
    });
  };

  const totalIncome = transactions
    .filter(t => t.type === 'income')
    .reduce((sum, t) => sum + t.amount, 0);

  const totalExpense = transactions
    .filter(t => t.type === 'expense')
    .reduce((sum, t) => sum + t.amount, 0);

  const balance = totalIncome - totalExpense;

  if (!user) {
    return <div className="p-6">Carregando...</div>;
  }

  return (
    <div className="p-6 w-full max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-8">
        <h1 className="text-3xl font-bold flex items-center gap-2">
          <Wallet className="w-8 h-8" />
          Finanças
        </h1>
        <button
          onClick={() => { resetForm(); setShowForm(true); }}
          className="px-4 py-2 rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 flex items-center gap-2"
        >
          <Plus className="w-5 h-5" />
          Nova Transação
        </button>
      </div>

      <div className="grid grid-cols-3 gap-4 mb-8">
        <div className="p-4 rounded-lg border bg-card">
          <div className="flex items-center gap-2 text-green-600 mb-2">
            <TrendingUp className="w-5 h-5" />
            <span className="text-sm font-medium">Receitas</span>
          </div>
          <p className="text-2xl font-bold text-green-600">
            {totalIncome.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}
          </p>
        </div>
        <div className="p-4 rounded-lg border bg-card">
          <div className="flex items-center gap-2 text-red-600 mb-2">
            <TrendingDown className="w-5 h-5" />
            <span className="text-sm font-medium">Despesas</span>
          </div>
          <p className="text-2xl font-bold text-red-600">
            {totalExpense.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}
          </p>
        </div>
        <div className="p-4 rounded-lg border bg-card">
          <div className="flex items-center gap-2 text-primary mb-2">
            <Wallet className="w-5 h-5" />
            <span className="text-sm font-medium">Saldo</span>
          </div>
          <p className={`text-2xl font-bold ${balance >= 0 ? 'text-green-600' : 'text-red-600'}`}>
            {balance.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}
          </p>
        </div>
      </div>

      <div className="space-y-2">
        {loading ? (
          <div className="text-center py-8 text-muted-foreground">Carregando...</div>
        ) : transactions.length === 0 ? (
          <div className="text-center py-8 text-muted-foreground bg-muted/20 rounded-lg border border-dashed">
            <p>Nenhuma transação encontrada.</p>
            <p className="text-sm mt-2">Registre suas receitas e despesas.</p>
          </div>
        ) : (
          transactions.map((transaction) => (
            <div key={transaction.id} className="flex items-center gap-4 p-4 rounded-lg border bg-card">
              <div className={`w-10 h-10 rounded-full flex items-center justify-center ${
                transaction.type === 'income' ? 'bg-green-100 text-green-600' : 'bg-red-100 text-red-600'
              }`}>
                {transaction.type === 'income' ? <TrendingUp className="w-5 h-5" /> : <TrendingDown className="w-5 h-5" />}
              </div>
              <div className="flex-1">
                <p className="font-medium">{transaction.description}</p>
                <div className="flex gap-2 mt-1">
                  {transaction.category && (
                    <span className="text-xs bg-muted px-2 py-0.5 rounded">{transaction.category}</span>
                  )}
                  <span className="text-xs text-muted-foreground">
                    {new Date(transaction.date).toLocaleDateString('pt-BR')}
                  </span>
                </div>
              </div>
              <p className={`font-bold ${transaction.type === 'income' ? 'text-green-600' : 'text-red-600'}`}>
                {transaction.type === 'income' ? '+' : '-'}
                {transaction.amount.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}
              </p>
              <button onClick={() => editTransaction(transaction)} className="p-2 text-muted-foreground hover:text-primary">
                <Edit2 className="w-4 h-4" />
              </button>
              <button onClick={() => deleteTransaction(transaction.id)} className="p-2 text-muted-foreground hover:text-destructive">
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          ))
        )}
      </div>

      {showForm && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-card p-6 rounded-lg w-full max-w-md space-y-4">
            <h2 className="text-xl font-bold">{editingTransaction ? 'Editar' : 'Nova'} Transação</h2>

            <div>
              <label className="block text-sm font-medium mb-1">Descrição</label>
              <input
                type="text"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                className="w-full px-4 py-2 rounded-lg border border-input bg-background"
                placeholder="Descrição da transação"
                autoFocus
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">Valor</label>
              <input
                type="number"
                step="0.01"
                value={formData.amount}
                onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                className="w-full px-4 py-2 rounded-lg border border-input bg-background"
                placeholder="0.00"
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">Tipo</label>
              <select
                value={formData.type}
                onChange={(e) => setFormData({ ...formData, type: e.target.value as 'income' | 'expense' })}
                className="w-full px-4 py-2 rounded-lg border border-input bg-background"
              >
                <option value="expense">Despesa</option>
                <option value="income">Receita</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">Categoria (opcional)</label>
              <input
                type="text"
                value={formData.category}
                onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                className="w-full px-4 py-2 rounded-lg border border-input bg-background"
                placeholder="Ex: Alimentação, Transporte..."
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">Data</label>
              <input
                type="date"
                value={formData.date}
                onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                className="w-full px-4 py-2 rounded-lg border border-input bg-background"
              />
            </div>

            <div className="flex gap-2 pt-4">
              <button
                onClick={saveTransaction}
                className="flex-1 px-4 py-2 rounded-lg bg-primary text-primary-foreground hover:bg-primary/90"
              >
                {editingTransaction ? 'Salvar' : 'Adicionar'}
              </button>
              <button
                onClick={resetForm}
                className="flex-1 px-4 py-2 rounded-lg border border-input hover:bg-accent"
              >
                Cancelar
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
